version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Argentina/Buenos_Aires"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    groups:
      gradle-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Argentina/Buenos_Aires"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    groups:
      github-actions:
        patterns:
          - "*"
